@echo off

#:: Set paths and variables
#SET EF_PROJECT_PATH=../DatabaseLayer         :: Relative path to DatabaseLayer.csproj
#SET STARTUP_PROJECT_PATH=.                   :: Current folder for TradingAPIs.csproj
#SET CONFIGURATION=Release                    :: Configuration (Release or Debug)
#SET DB_CONNECTION_STRING="Host=oregon-postgres.render.com;Port=5432;Database=trade_pgs_db;Username=trade_pgs_db_user;Password=1O4gXP71zC1O8qbo94tJwwGOGT3LwxCT;SslMode=Require"  :: Replace this with your actual connection string
#set CONTEXT_NAME=AppDbContext                       :: Replace with your DbContext name

@echo off

:: Set variables
set PROJECT_DIR=.
set MIGRATION_NAME=AutoGeneratedMigration
set DB_CONTEXT=AppDbContext
set PIPELINE_OUTPUT_DIR=../DatabaseLayer/Migrations

:: Step 1: Development Environment
cd %PROJECT_DIR%
echo Running Entity Framework updates in Development Environment...

:: Remove previous migration if necessary
if exist "%PROJECT_DIR%\Migrations\%MIGRATION_NAME%.cs" (
    echo Removing previous migration...
    dotnet ef migrations remove -c %DB_CONTEXT% -f
)

:: Add new migration
echo Adding new migration...
dotnet ef migrations add %MIGRATION_NAME% -c %DB_CONTEXT%

:: Update the database
echo Updating the database...
dotnet ef database update -c %DB_CONTEXT%

:: Step 2: Git Pipeline Preparation
echo Preparing migrations for Git pipeline...

:: Ensure pipeline output directory exists
if not exist "%PIPELINE_OUTPUT_DIR%" (
    mkdir "%PIPELINE_OUTPUT_DIR%"
)

:: Copy migrations to pipeline directory
xcopy /Y /E "%PROJECT_DIR%\Migrations" "%PIPELINE_OUTPUT_DIR%"

:: Completion message
echo Entity Framework updates and migrations have been completed.
pause

