name: Build and deploy ASP.NET Core app to Azure Web App

env:
  AZURE_WEBAPP_NAME: trade-api         # Name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './TradingAPIs' # Path to the web app project (relative to the repository root)
  DOTNET_VERSION: '8'                     # .NET Core version to use

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET Core environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Set up caching for dependencies
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Step 4: Build the project
      - name: Build the project
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build --configuration Release

      # Step 5: Publish the project
      - name: Publish the project
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet publish --configuration Release --output ./publish

      # Step 6: Upload artifact for deployment
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download artifact from the build job
      - name: Download deployment artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app

      # Step 2: Deploy to Azure Web App using publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
