name: Deploy React App to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd TradingAPIs/ui-layer
          npm install

      - name: Build React app
        run: |
          cd TradingAPIs/ui-layer
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: TradingAPIs/ui-layer/build
      - name: Push to GitHub Pages
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_ADMIN }}@github.com/SahasraSynergy/AllTradeAPIs.git
          git push origin gh-pages

